#!/usr/bin/env python3
"""Portable hook (PreToolUse, matcher Write|Edit) — protects GENERATED artifacts.

Payload of the ``quenching-management`` method. Generic and self-contained.
Materializes the axis of **deterministic enforcement** of dim 14 (guardrails)
crossing dim 8 (hooks): the method's doctrine — "keeps generated artifacts
intact" / rule «X defines Y» (the source is the truth, the generated is disposable) —
applied **before** the edit, by code, not by trust in the LLM's judgment.

It is the **enforcement complement** of the PostToolUse ``propose-docs-home`` (which
PROPOSES *after*): this one **BLOCKS before**. When a Write/Edit targets a
**generated/protected** artifact of the target (generated YAML/manifests, AUTO-GENERATED
catalog, lockfiles — the list is **derived from the target** via ``protectedGlobs``, NEVER paths
from this repo), the hook **cancels the edit** with an **actionable** error that says the
**source-of-truth** to edit instead of the generated file.

Distinct from the sibling hooks:
- ``propose-knowledge-delta`` (Stop), ``reinject-conventions`` (SessionStart),
  ``audit-config-change`` (ConfigChange): fire by **moment** (end of turn /
  restart / config change) and never block.
- ``propose-docs-home`` (PostToolUse): also a tool event, but runs
  **after** the tool succeeded and **"Can block? No"** — only PROPOSES.
- **This one (PreToolUse) runs BEFORE the tool and CAN block** ("Can block? Yes"). It is the
  only **enforcement** payload on the surface; the others OBSERVE/PROPOSE.

Official contract (PreToolUse — code.claude.com/docs/en/hooks#pretooluse):

- **Fires BEFORE the tool executes and CAN block it** (*"Before a tool call
  executes. Can block it"*). Matcher = **tool name** (``"Edit|Write"``).
  The input JSON carries ``tool_name`` and ``tool_input.file_path``.
- **Modern blocking form (the one we use):** return JSON
  ``hookSpecificOutput.permissionDecision: "deny"`` + ``permissionDecisionReason``
  with **exit 0** — *"With `deny`, Claude Code cancels the tool call and feeds
  `permissionDecisionReason` back to Claude"*. ``deny`` wins even in
  ``bypassPermissions`` / ``--dangerously-skip-permissions`` (*"PreToolUse hooks
  fire before any permission-mode check"*) — enforcement the user cannot bypass
  by switching the permission mode. **Legacy form (fallback, if runtime ignores the
  JSON):** ``exit 2`` + reason in ``stderr`` — *"Exit 2: the action is blocked.
  Write a reason to stderr"* (the exit-codes table marks PreToolUse "Can block?
  Yes" / *"Blocks the tool call"*). We do **not** mix the two forms in the same
  path: the docs warn *"Don't mix them: Claude Code ignores JSON when you exit 2"*
  — we emit the JSON (exit 0) **or** exit 2, never both.
- **Actionable error (dim 14).** The reason says **WHICH** source-of-truth
  GENERATES that artifact and instructs to edit the source (the docs: *"Claude receives it as
  feedback so it can adjust its approach"*) — never a silent code. Without this, the
  agent loops: retries editing the generated file blindly.
- **Latency ceiling (~500 ms on the critical path).** Only matches the path string
  against ``protectedGlobs`` (``fnmatch``) — no file I/O. PreToolUse runs on
  EVERY Write/Edit: slow here = every edit slow. ``deadlineMs`` as guard.

Pre-trust vector: hook config is **executable code** with shell privileges.
This script is **read-only** (reads the touched path; writes nothing) —
version and review it like infra. Register the ``command`` in ``settings.json`` under the
``PreToolUse`` event with ``matcher: "Write|Edit"`` (use ``settings.snippet.json``).
Honors ``hooks-config.json``/``hooks-config.local.json`` (block ``protectGenerated``):
``enabled: false`` exits silently (blocks nothing).

PORTABILITY — derive ``protectedGlobs``/``sourceHint`` from the target, NEVER hardcode:
``protectedGlobs`` is the list of **generated artifact** patterns of the TARGET REPO
(discovered in Step 1: what the repo's «X defines Y» rule marks as
"generated by CI, never edited by hand"). ``sourceHint`` maps, by glob, the
**source-of-truth** to edit instead (the actionable message). Nothing in this file
names a path from this repo: the empty list (default) = inert hook. Examples only
in the comment of ``settings.snippet.json``/``hooks-config.json``.
"""
from __future__ import annotations

import fnmatch
import json
import os
import pathlib
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
TAG = "knowledge-management"

DEFAULTS: dict = {
    "enabled": True,
    # GENERATED artifact patterns of the target (derived in Step 1). Empty = inert.
    # Ex. (NOT from this repo; illustrates the form): ["**/yamls/*.job.yml",
    #     "**/*.schema.yml", "**/tasks_manifest.json", "**/*.lock"]
    "protectedGlobs": [],
    # Glob → source-of-truth to edit map (actionable message). Optional;
    # matches the first glob that hits. No entry ⇒ generic hint.
    # Ex.: {"**/yamls/*.job.yml": "the Job subclass in <source>/jobs/ (CI re-generates the YAML)"}
    "sourceHint": {},
    # Output mode: "deny" (modern JSON, recommended) | "exit2" (legacy/stderr).
    "denyMode": "deny",
    "deadlineMs": 100,  # string matching only; no I/O
}


def _load_config() -> dict:
    cfg = dict(DEFAULTS)
    for name in ("hooks-config.json", "hooks-config.local.json"):
        path = os.path.join(HERE, name)
        if not pathlib.Path(path).exists():
            continue
        try:
            with pathlib.Path(path).open(encoding="utf-8") as fh:
                data = json.load(fh)
        except (OSError, json.JSONDecodeError):
            continue
        cfg.update(data.get("protectGenerated") or {})
    return cfg


def _read_input() -> dict:
    try:
        return json.loads(sys.stdin.read() or "{}")
    except (OSError, json.JSONDecodeError):
        return {}


def _project_dir(data: dict) -> str:
    return os.environ.get("CLAUDE_PROJECT_DIR") or data.get("cwd") or os.getcwd()


def _rel_path(file_path: str, root: str) -> str:
    """Path relative to the project root, with '/' — to match the globs."""
    abspath = file_path if os.path.isabs(file_path) else os.path.join(root, file_path)
    norm = os.path.normpath(abspath)
    root_norm = os.path.normpath(root)
    if norm.startswith(root_norm + os.sep):
        rel = os.path.relpath(norm, root_norm)
    else:
        rel = norm  # outside root: match by absolute path
    return rel.replace(os.sep, "/")


def _matched_glob(rel: str, base: str, globs: list[str]) -> str | None:
    """First glob that matches the path (relative to root) or the basename. None = free."""
    for pat in globs:
        # matches the full path (e.g. **/yamls/*.job.yml) OR just the name (e.g. *.lock)
        if fnmatch.fnmatch(rel, pat) or fnmatch.fnmatch(base, pat):
            return pat
    return None


def _reason(rel: str, pat: str, source_hint: dict) -> str:
    """ACTIONABLE reason: names the source-of-truth to edit instead of the generated file."""
    src = source_hint.get(pat)
    if not src:
        src = (
            "the SOURCE-OF-TRUTH that generates this artifact (the repo's «X defines Y» rule) "
            "— edit the source and re-run the generator/CI; this file will be overwritten"
        )
    return (
        f"[{TAG}] Edit BLOCKED: '{rel}' matches the GENERATED artifact pattern "
        f"'{pat}'. Generated artifacts are disposable (rule «X defines Y» / doctrine "
        f"\"keeps generated intact\"): editing them by hand is lost on the next "
        f"generation. Edit instead: {src}. "
        "If this file should NOT be treated as generated, adjust 'protectedGlobs' "
        "in hooks-config.json (do not force the edit)."
    )


def _deny_json(reason: str) -> None:
    """MODERN form: deny + permissionDecisionReason, exit 0 (do not mix with exit 2)."""
    payload = {
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "deny",
            "permissionDecisionReason": reason,
        }
    }
    print(json.dumps(payload))


def main() -> int:
    cfg = _load_config()
    if cfg.get("enabled") is False:
        return 0

    globs = cfg.get("protectedGlobs") or []
    if not globs:  # no target-derived list ⇒ inert hook (blocks nothing)
        return 0

    data = _read_input()
    started = time.monotonic()
    deadline = float(cfg.get("deadlineMs", DEFAULTS["deadlineMs"])) / 1000.0

    tool_input = data.get("tool_input") or {}
    file_path = tool_input.get("file_path") or ""
    if not file_path:
        return 0  # no file target ⇒ let the normal permission flow decide

    root = _project_dir(data)
    rel = _rel_path(file_path, root)
    base = os.path.basename(rel)

    if time.monotonic() - started > deadline:
        return 0  # deadline exceeded: do not delay the edit (fail-open for latency)

    pat = _matched_glob(rel, base, globs)
    if pat is None:
        return 0  # not generated ⇒ exit 0 does NOT approve; normal permission flow continues

    reason = _reason(rel, pat, cfg.get("sourceHint") or {})
    if (cfg.get("denyMode") or "deny") == "exit2":
        # LEGACY form: stderr + exit 2 (docs: "Write a reason to stderr").
        print(reason, file=sys.stderr)
        return 2
    # MODERN form (recommended): JSON deny + exit 0. Wins even in bypassPermissions.
    _deny_json(reason)
    return 0


if __name__ == "__main__":
    sys.exit(main())
